### PR TITLE
Bump max version to 25 + Migrate to Application Bootstrap

### LINKED ISSUE #20: HSTS Header doesn’t exist for Nextcloud 24 (and 25)
Hello,

I want to migrate to the 24th branch of Nextcloud, but I have this message since several months:

HSTS Header doesn’t exist for Nextcloud 24.

I have ask my web hosting (Infomaniak) and I have no headers activated.

I have deactivate the module this morning, to test my Nextcloud without the module.

I have two choice now:
— wait since HSTS Header create a new version that support Nextcloud 24, than migrate to it
— desactivate the apps and migrate, and perhaps have a security problem

What shloud I do, please? Do you can do somethings for Nextcloud user that have shared server?

Thanks.

### PR DESCRIPTION
**Pull request by Indigo744**
Fixes #20

### CODE REVIEW

**Comment by sualko** [comment]
Thanks for your contribution. Do you think it would be possible that you could extend this pull request by moving from the app.php to https://docs.nextcloud.com/server/latest/developer_manual/app_development/bootstrap.html?

**Comment by Indigo744** [comment]
I've never done any NextCloud development before, but I do know some PHP so I'll look into it.

If I understand correctly after a quick search, `app.php` is the older (and deprecated) way of doing NextCloud App and the new way implies a new architecture involving a class inherited from `IBootstrap`.

Alright, I'll try to come up with something 😺

**Comment by Indigo744** [comment]
Done! You can do a code review.

I've tested on my own 23.0 instance (with various `hsts.*` config values), it works as intended.

**Comment by Indigo744** [comment]
I made a small enhancement in order to use NextCloud PHP API with dependency injection.

**Comment by sualko** [comment]
Looks great. I just have to test it before I merge it. Thanks a lot :+1:

**Comment by Indigo744** [comment]
Glad I could help 😸

**Comment by Indigo744** [comment]
Hello!
The package 0.10.0 on NextCloud repo is still in "beta" hence the update feature still warn about incompatibility for NC 24 or 25.
Any chance to release a final version?

Thanks a lot

**Pull request closed without merging**
